### ISSUE TITLE
Creating Payment Service

### ISSUE THREAD

**Issue by BeyzaAcar** [DevOps-Calisma/acme-books#6]
5. Payment Service
Issue Title: Implement Payment Service

Description:
The Payment Service will handle payment processing for orders. It will allow users to initiate payments for placed orders.

Tasks:
Set up a Node.js application with Express:

Create the Payment Service using Node.js and Express.
Set up the project structure with templates and static directories.
Create REST API for payment processing:

Implement a POST endpoint /process-payment that accepts payment details (e.g., order_id, payment_method, amount) and processes the payment.
Build a simple HTML form for initiating payments:

Create payment_form.html to allow users to enter payment details via a form.
Use JavaScript (script.js) to handle form submission and send data via a POST request to the /process-payment endpoint.
Run the service on a specified port:

Ensure the service runs on localhost:5005 or any available port.
Include proper error handling for invalid payment details.
Acceptance Criteria:
The /process-payment API endpoint works correctly and returns a success response after logging the payment details.
The HTML form is functional and can process payments.
The service is ready for Docker integration.

**Comment by omerdr1** [comment]
This issue has been canceled
